FROM websphere/websphere
COPY Sample1.war  /config/dropins/Sample1.war
ADD https://github.com/WASdev/sample.plantsbywebsphere/blob/master/PlantsByWebSphereV8/lib/pbw-lib.jar /config/dropins/pbw-lib.jar
#ADD https://github.com/IBM-Cloud/java-helloworld/blob/master/target/JavaHelloWorldApp.war   /config/dropins/helloworld.war

