FROM websphere/websphere
ADD https://publib.boulder.ibm.com/bpcsamp/gettingStarted/helloWorld/download/HelloWorldApp.ear /config/dropins/HelloWorldApp.ear
ADD https://github.com/IBM-Cloud/java-helloworld/blob/master/target/JavaHelloWorldApp.war   /config/dropins/helloworld.war

